@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
    Interface ReadOnlyGradeBook <<Interface>>
    Interface Model <<Interface>>
    Interface ObservableList <<Interface>>
    Class GradeBook
    Class ReadOnlyGradeBook
    Class Model
    Class ModelManager
    Class UserPrefs
    Class ReadOnlyUserPrefs

Package Module {
    Class Module
    Class ModuleName
    Class ModularCredit
    Class Grade
    Class UniqueModuleList
}

Package Semester {
    Class SemesterManager
    Enum Semester <<Enumeration>>
}

SemesterManager --> Semester

Package GoalTarget {
    Class GoalTarget
    Enum Cap <<Enumeration>>
}
GoalTarget --> Cap

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

GradeBook .up.|> ReadOnlyGradeBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" GradeBook
ModelManager o--> "0..1" GoalTarget
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

GradeBook *--> "1" UniqueModuleList
UniqueModuleList o--> "*" Module
Module *--> ModuleName
Module *--> ModularCredit
Module *--> Grade

ModelManager ----->"1" Module : filtered list
ModelManager --->"1" SemesterManager
@enduml
